export const CONSTANTS = {
  SUPPORTED_MIME_TYPES: ['application/pdf', 'image/jpeg', 'image/png'] as const,
  MAX_FILE_SIZE_BYTES: 5 * 1024 * 1024, // 5MB
  MAX_IMAGE_DIMENSION: 2500, // max longest edge in px
  MIN_EXTRACTED_CHARACTERS: 300,
  MIN_OCR_CONFIDENCE: 0.70,
  MIN_ALPHABETIC_RATIO: 0.50,
  MAX_PDF_PAGES: 2,

  EVIDENCE_LEVEL_WEIGHTS: {
    absent: 0.00,
    mentioned: 0.35,
    practised: 0.60,
    demonstrated: 0.80,
    applied: 1.00,
  } as const,

  ERROR_CODES: {
    UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    TOO_MANY_PAGES: 'TOO_MANY_PAGES',
    PDF_PASSWORD_PROTECTED: 'PDF_PASSWORD_PROTECTED',
    RESUME_TEXT_INSUFFICIENT: 'RESUME_TEXT_INSUFFICIENT',
    IMAGE_TOO_BLURRY: 'IMAGE_TOO_BLURRY',
    OCR_UNAVAILABLE: 'OCR_UNAVAILABLE',
    OCR_TIMEOUT: 'OCR_TIMEOUT',
    ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
    QUESTIONNAIRE_INVALID: 'QUESTIONNAIRE_INVALID',
    ANALYSIS_PROVIDER_UNAVAILABLE: 'ANALYSIS_PROVIDER_UNAVAILABLE',
    ANALYSIS_RESPONSE_INVALID: 'ANALYSIS_RESPONSE_INVALID',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
  } as const,
};
